"use client";
import { useLiveQuery } from "dexie-react-hooks";
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { db } from "@/lib/db";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
export default function ProgressPage(){
const completions=useLiveQuery(()=>db.completions.orderBy("completedAt").toArray(),[],[]),attributes=useLiveQuery(()=>db.attributes.orderBy("order").toArray(),[],[]),profile=useLiveQuery(()=>db.profile.get("me"),[]);
const valid=completions.filter(i=>!i.revokedAt);const days=Array.from({length:14},(_,index)=>{const date=new Date();date.setDate(date.getDate()-13+index);const key=date.toISOString().slice(0,10);return{day:key.slice(5),xp:valid.filter(i=>i.completedAt.slice(0,10)===key).reduce((sum,i)=>sum+i.spiritualityAwarded,0)}});
const quality=["missed","done","good","excellent"].map((q,index)=>({name:["未达成","完成","良好","卓越"][index],value:valid.filter(i=>i.quality===q).length,color:["#bd635c","#72947f","#b49a5e","#7faaa7"][index]}));
const attr=attributes.map(i=>({name:i.name,xp:i.xp,color:i.color}));const actual=valid.map(i=>({name:i.questTitle.slice(0,8),actual:i.actualMinutes}));
return <div className="space-y-6"><div><p className="text-xs tracking-[.28em] text-brass">PROGRESS · 命运轨迹</p><h1 className="serif mt-2 text-3xl">从账本中观察命运留下的真实轨迹</h1><p className="mt-2 text-sm text-muted">累计灵性经验 {profile?.totalSpirituality??0}；有效结算 {valid.length} 次。</p></div>
<div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><div><h2 className="serif text-xl">近 14 天灵性经验</h2><p className="mt-1 text-xs text-muted">从任务结算账本聚合。</p></div></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={days}><CartesianGrid stroke="rgba(180,154,94,.12)" vertical={false}/><XAxis dataKey="day" stroke="#8e9a91" fontSize={11}/><YAxis stroke="#8e9a91" fontSize={11}/><Tooltip contentStyle={{background:"#101a1b",border:"1px solid rgba(180,154,94,.3)",borderRadius:8}}/><Bar dataKey="xp" fill="#b49a5e" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></CardContent></Card>
<Card><CardHeader><div><h2 className="serif text-xl">完成质量分布</h2><p className="mt-1 text-xs text-muted">质量影响消化，但不会隐藏计算。</p></div></CardHeader><CardContent className="h-72"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={quality} dataKey="value" nameKey="name" innerRadius={55} outerRadius={90} paddingAngle={4}>{quality.map(i=><Cell key={i.name} fill={i.color}/>)}</Pie><Tooltip contentStyle={{background:"#101a1b",border:"1px solid rgba(180,154,94,.3)",borderRadius:8}}/></PieChart></ResponsiveContainer></CardContent></Card></div>
<div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><h2 className="serif text-xl">属性经验</h2></CardHeader><CardContent className="space-y-4">{attr.map(i=><div key={i.name}><div className="mb-1 flex justify-between text-xs"><span>{i.name}</span><span className="text-muted">{i.xp}</span></div><div className="h-2 overflow-hidden rounded-full bg-black/25"><div className="h-full rounded-full" style={{width:Math.min(100,i.xp/10)+"%",background:i.color}}/></div></div>)}</CardContent></Card>
<Card><CardHeader><div><h2 className="serif text-xl">实际用时记录</h2><p className="mt-1 text-xs text-muted">最近完成任务的实际分钟数。</p></div></CardHeader><CardContent className="h-72">{actual.length?<ResponsiveContainer width="100%" height="100%"><BarChart data={actual.slice(-10)}><CartesianGrid stroke="rgba(180,154,94,.12)" vertical={false}/><XAxis dataKey="name" stroke="#8e9a91" fontSize={10}/><YAxis stroke="#8e9a91" fontSize={11}/><Tooltip contentStyle={{background:"#101a1b",border:"1px solid rgba(180,154,94,.3)",borderRadius:8}}/><Bar dataKey="actual" fill="#7faaa7" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<div className="grid h-full place-items-center"><Badge>暂无结算数据</Badge></div>}</CardContent></Card></div></div>}

