import { NextResponse } from "next/server";
import { z } from "zod";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

const requestSchema = z.object({ context: z.record(z.string(), z.unknown()), draft: z.record(z.string(), z.unknown()) });

/**
 * Legacy endpoint. It no longer calls any AI provider: the adventure skeleton
 * (title, choices, reality-task proposals) is produced locally, and the long-form
 * chapter is generated by the opening turn through /api/adventure/turn.
 */
export async function POST(request: Request) {
  let payload: unknown;
  try {
    payload = await request.json();
  } catch {
    return NextResponse.json({ error: "请求体不是合法 JSON" }, { status: 400 });
  }
  const parsed = requestSchema.safeParse(payload);
  if (!parsed.success) return NextResponse.json({ error: "无效的请求" }, { status: 400 });
  return NextResponse.json({
    event: parsed.data.draft,
    mode: "local",
    provider: "local",
    model: "local-planner",
    deprecated: true,
    note: "开篇长文改由 /api/adventure/turn（phase=opening）生成。",
  });
}

