"use client";
import { useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { AlertTriangle, CheckCircle2, Circle, Shield, Sparkles } from "lucide-react";
import { db } from "@/lib/db";
import { calculateDigestionCap, calculateStatusAverage, statusBand } from "@/lib/domain/digestion";
import { STAGE_LABELS } from "@/lib/domain/sequence";
import { getPathway, getSequence } from "@/lib/lore/pathways";
import { applyLossOfControl, getActiveCharacterBackground, getActiveFateProfile, setRealityRequirement, transferPathway } from "@/lib/repository";
import { fateSummary } from "@/lib/wheel/engine";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { PathwayTarot } from "@/components/pathway-tarot";
import { SkillPanel } from "@/components/skill-panel";
import { InventoryPanel } from "@/components/inventory-panel";
import { RelationshipPanel } from "@/components/relationship-panel";
export default function CharacterPage(){
const [message,setMessage]=useState("");
const profile=useLiveQuery(()=>db.profile.get("me"),[]),state=useLiveQuery(()=>db.sequenceState.get("active"),[]),settings=useLiveQuery(()=>db.settings.get("app"),[]);
const background=useLiveQuery(()=>getActiveCharacterBackground(),[],null),fate=useLiveQuery(()=>getActiveFateProfile(),[],null);
const attributes=useLiveQuery(()=>db.attributes.orderBy("order").toArray(),[],[]),requirements=useLiveQuery(()=>db.realityRequirements.toArray(),[],[]),achievements=useLiveQuery(()=>db.achievements.toArray(),[],[]),items=useLiveQuery(()=>db.items.toArray(),[],[]),events=useLiveQuery(()=>db.stabilityEvents.orderBy("createdAt").reverse().limit(8).toArray(),[],[]);
if(!profile||!state||!settings||!state.pathwayId)return null;const pathway=getPathway(state.pathwayId),sequence=getSequence(state.pathwayId,state.sequence);if(!pathway||!sequence)return null;
const cap=calculateDigestionCap(state.sequence,settings),average=calculateStatusAverage(settings.status),band=statusBand(average),current=requirements.filter(i=>i.pathwayId===state.pathwayId&&i.sequence===state.sequence),adjacent=pathway.adjacentIds.map(getPathway).filter(Boolean);
async function lose(){if(!window.confirm("确认执行失控结算？会按公开规则损失消化度，严重时下降一个序列；历史不会删除。"))return;try{const r=await applyLossOfControl();setMessage(r.reason)}catch(e){setMessage(e instanceof Error?e.message:"无法结算")}}
async function transfer(id:string){if(!window.confirm("转途保留历史与属性，但当前消化度归零。"))return;try{const t=await transferPathway(id);setMessage("已转入"+t.name+"途径")}catch(e){setMessage(e instanceof Error?e.message:"转途失败")}}
return <div className="space-y-6">
<div><p className="text-xs tracking-[.28em] text-brass">CHARACTER · 非凡档案</p><h1 className="serif mt-2 text-3xl">{profile.name} · 序列 {state.sequence}</h1><p className="mt-2 text-sm text-muted">{pathway.name}途径 · 「{sequence.name}」 · {STAGE_LABELS[state.stage]}</p></div>
<Card><CardHeader><div className="flex flex-wrap items-center justify-between gap-2"><h2 className="serif text-xl">人物背景</h2>{background&&<Badge>{background.provider} · {background.model}</Badge>}</div></CardHeader><CardContent className="space-y-4">{background?<><div className="grid gap-2 text-sm sm:grid-cols-2">{(["姓名","年龄","职业","出身","外貌","性格","动机","秘密","随身物","弱点"] as const).map((label,index)=>{const value=[background.fields.name,background.fields.age,background.fields.occupation,background.fields.origin,background.fields.appearance,background.fields.personality,background.fields.motive,background.fields.secret,background.fields.keepsake,background.fields.weakness][index];return <div key={label} className="rounded-md border border-border bg-panel-soft p-3"><p className="text-[10px] text-muted">{label}</p><p className="mt-1 leading-6">{value}</p></div>})}</div><div className="rounded-md border border-brass/30 bg-brass/5 p-4"><p className="whitespace-pre-wrap font-serif text-sm leading-7">{background.backgroundText}</p></div>{fate&&<p className="text-xs text-muted">命运：{fateSummary(fate)}</p>}<p className="text-[11px] text-muted">生成于 {new Date(background.createdAt).toLocaleString("zh-CN")}。重新抽转盘会新建人物档案，旧档案归档为前史。</p></>:<p className="text-sm text-muted">还没有人物背景。去「命运转盘」抽取命运后即可生成。</p>}</CardContent></Card><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card><CardContent className="grid gap-6 sm:grid-cols-[auto_1fr]"><div className="mx-auto w-[190px] max-w-full sm:w-[220px]"><PathwayTarot pathway={pathway}/></div><div><div className="flex flex-wrap gap-2"><Badge>{pathway.tarot}</Badge><Badge>{pathway.sefirah}</Badge><Badge>资料状态 · {sequence.loreStatus}</Badge></div><h2 className="serif mt-4 text-3xl">{sequence.name}</h2><p className="mt-3 text-sm leading-6 text-muted">{sequence.abilities[0]}</p><div className="mt-5"><div className="mb-2 flex justify-between text-xs"><span className="text-muted">魔药消化度</span><span>{state.digestion} / {cap}</span></div><Progress value={state.digestion} max={cap}/></div></div></CardContent></Card>
<Card><CardHeader><div><h2 className="serif text-lg">稳定度</h2><p className="mt-1 text-xs text-muted">当前平均 {average}</p></div><Badge>{band.label}</Badge></CardHeader><CardContent><div className="grid grid-cols-4 gap-2 text-center">{[["SAN",settings.status.san],["体力",settings.status.energy],["专注",settings.status.focus],["动力",settings.status.motivation]].map(([l,v])=><div key={l} className="panel-soft rounded-md p-3"><div className="text-[11px] text-muted">{l}</div><div className="mt-1 text-lg">{v}</div></div>)}</div><Button variant="danger" className="mt-4 w-full" disabled={average>=15} onClick={lose}><AlertTriangle className="size-4"/>确认失控结算</Button>{message&&<p className="mt-3 text-xs gold-text">{message}</p>}</CardContent></Card></div>
<div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><h2 className="serif text-xl">序列阶梯</h2></CardHeader><CardContent className="space-y-2">{pathway.sequences.map(i=><div key={i.id} className={"flex items-center justify-between rounded-md border px-3 py-2 text-sm "+(i.sequence===state.sequence?"border-brass/50 bg-brass/10":"border-transparent")}><span className="flex items-center gap-2">{i.sequence<state.sequence?<CheckCircle2 className="size-4 text-moss"/>:i.sequence===state.sequence?<Sparkles className="size-4 text-brass-bright"/>:<Circle className="size-4 text-muted"/>}序列 {i.sequence}</span><span>{i.name}</span></div>)}</CardContent></Card>
<Card><CardHeader><h2 className="serif text-xl">现实晋升条件</h2></CardHeader><CardContent className="space-y-3">{current.map(i=><label key={i.id} className="flex cursor-pointer gap-3 rounded-md border border-border bg-panel-soft p-3"><input type="checkbox" checked={i.completed} onChange={e=>setRealityRequirement(i.id,e.target.checked)} className="mt-1"/><span><span className="text-sm">{i.title}</span><span className="mt-1 block text-xs text-muted">{i.description}</span><Badge className="mt-2">{i.kind}</Badge></span></label>)}{[4,3].includes(state.sequence)&&adjacent.length>0&&<div className="border-t border-border pt-4"><p className="mb-2 text-xs text-muted">相邻转途可选</p>{adjacent.map(t=>t&&<Button key={t.id} size="sm" variant="secondary" className="mr-2" onClick={()=>transfer(t.id)}>{t.name}途径</Button>)}</div>}</CardContent></Card></div>
<div className="grid gap-5 lg:grid-cols-3"><Card><CardHeader><h2 className="serif text-lg">核心属性</h2></CardHeader><CardContent className="space-y-4">{attributes.map(i=><div key={i.id}><div className="mb-1 flex justify-between text-xs"><span>{i.name}</span><span className="text-muted">{i.xp} XP</span></div><div className="h-1.5 overflow-hidden rounded-full bg-black/25"><div className="h-full rounded-full" style={{width:Math.min(100,i.xp/10)+"%",background:i.color}}/></div></div>)}</CardContent></Card><SkillPanel/><InventoryPanel/><RelationshipPanel/>
<Card><CardHeader><h2 className="serif text-lg">成就与徽章</h2></CardHeader><CardContent className="space-y-3">{achievements.map(i=><div key={i.id} className="flex gap-3"><Shield className={"mt-0.5 size-4 "+(i.unlockedAt?"text-brass-bright":"text-muted")}/><div><p className="text-sm">{i.name}</p><p className="mt-1 text-xs text-muted">{i.unlockedAt?i.description:"未解锁 · "+i.rule}</p></div></div>)}</CardContent></Card>
<Card><CardHeader><h2 className="serif text-lg">非凡物品与记录</h2></CardHeader><CardContent><div className="space-y-3">{items.map(i=><div key={i.id} className={i.unlockedAt?"":"opacity-45"}><p className="text-sm">{i.name}</p><p className="mt-1 text-xs text-muted">{i.unlockedAt?i.description:"尚未获得"}</p></div>)}</div><div className="mt-5 border-t border-border pt-4">{events.slice(0,4).map(e=><div key={e.id} className="flex justify-between text-xs"><span>{new Date(e.createdAt).toLocaleDateString("zh-CN")}</span><span>{e.eventType==="loss_of_control"?"失控结算":"状态记录"} · {e.average}</span></div>)}</div></CardContent></Card></div>
</div>}




