"use client";
import { useEffect, useRef, useState } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { BrainCircuit, Download, HardDriveDownload, Save, ShieldCheck, Trash2, Upload } from "lucide-react";
import { db } from "@/lib/db";
import { clearDatabase, exportBackup, exportQuestsCsv, importBackup, importQuestsCsv } from "@/lib/repository";
import type { ImportableBackup } from "@/lib/types";
import { getAdventureStatus, type AdventureStatus } from "@/lib/adventure/service";
import { PersonalProfileDialog } from "@/components/personal-profile-dialog";
import { AISettingsPanel } from "@/components/ai-settings-panel";
import { AIUsagePanel } from "@/components/ai-usage-panel";
import { ContentAuditPanel } from "@/components/content-audit-panel";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader } from "@/components/ui/card";
import { Input, Label, Select } from "@/components/ui/form";
export default function SettingsPage(){
const profile=useLiveQuery(()=>db.profile.get("me"),[]),personalProfile=useLiveQuery(()=>db.personalProfile.get("me"),[]),settings=useLiveQuery(()=>db.settings.get("app"),[]),quests=useLiveQuery(()=>db.quests.count(),[],0),completions=useLiveQuery(()=>db.completions.count(),[],0),aiLogs=useLiveQuery(()=>db.aiRequestLogs.orderBy("createdAt").reverse().limit(8).toArray(),[],[]);
const [message,setMessage]=useState("");const [profileOpen,setProfileOpen]=useState(false);const [adventureStatus,setAdventureStatus]=useState<AdventureStatus|null>(null);const jsonInput=useRef<HTMLInputElement>(null),csvInput=useRef<HTMLInputElement>(null);
useEffect(()=>{getAdventureStatus().then(setAdventureStatus)},[]);
if(!profile||!personalProfile||!settings)return null;
function download(name:string,content:string,type:string){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=name;link.click();URL.revokeObjectURL(url)}
async function saveProfile(form:FormData){await db.profile.update("me",{name:String(form.get("name")||"调查员"),updatedAt:new Date().toISOString()});setMessage("角色信息已保存")}
async function saveSettings(form:FormData){await db.settings.update("app",{timezone:String(form.get("timezone")),digestionBase:Number(form.get("base")),digestionLinear:Number(form.get("linear")),digestionQuadratic:Number(form.get("quadratic")),theme:String(form.get("theme")) as "dark"|"light",animations:form.get("animations")==="on",chapterLength:String(form.get("chapterLength")) as "brief"|"standard"|"long",allowNonCanonGeo:form.get("allowNonCanonGeo")==="on",updatedAt:new Date().toISOString()});setMessage("公式与偏好已保存")}
async function doExport(){const backup=await exportBackup();download("sequence-log-backup.json",JSON.stringify(backup,null,2),"application/json");setMessage("JSON 备份已导出")}
async function doImport(file:File){try{const snapshot=JSON.parse(await file.text()) as ImportableBackup;if(!window.confirm("导入会替换当前全部数据。确认继续？"))return;await importBackup(snapshot);window.location.reload()}catch(error){setMessage(error instanceof Error?error.message:"导入失败")}}
async function doCsvExport(){download("sequence-quests.csv",await exportQuestsCsv(),"text/csv;charset=utf-8");setMessage("任务 CSV 已导出")}
async function doCsvImport(file:File){const count=await importQuestsCsv(await file.text());setMessage("已导入 "+count+" 行任务数据")}
async function wipe(){const value=window.prompt("此操作会删除全部本地数据。请输入“清除全部”确认：");if(value!=="清除全部")return;await clearDatabase();window.location.reload()}
return <div className="space-y-6"><div><p className="text-xs tracking-[.28em] text-brass">SETTINGS · 幕后控制台</p><h1 className="serif mt-2 text-3xl">幕后控制台与数据保险箱</h1><p className="mt-2 text-sm text-muted">所有核心数据保存在当前浏览器的 IndexedDB；备份是长期使用时的必要保障。</p></div>{message&&<div className="rounded-md border border-brass/30 bg-brass/10 p-3 text-sm gold-text">{message}</div>}
<div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><h2 className="serif text-xl">角色信息</h2></CardHeader><CardContent><form action={saveProfile} className="space-y-4"><div><Label>角色名</Label><Input name="name" defaultValue={profile.name}/></div><div><Label>当前称号</Label><Input value={profile.title} readOnly disabled/></div><Button type="submit"><Save className="size-4"/>保存角色信息</Button></form></CardContent></Card>
<Card><CardHeader><h2 className="serif text-xl">公式与偏好</h2></CardHeader><CardContent><form action={saveSettings} className="space-y-4"><div className="grid gap-4 sm:grid-cols-3"><div><Label>基础消化</Label><Input name="base" type="number" defaultValue={settings.digestionBase}/></div><div><Label>线性增长</Label><Input name="linear" type="number" defaultValue={settings.digestionLinear}/></div><div><Label>平方增长</Label><Input name="quadratic" type="number" defaultValue={settings.digestionQuadratic}/></div></div><div className="grid gap-4 sm:grid-cols-2"><div><Label>时区</Label><Select name="timezone" defaultValue={settings.timezone}><option value="Asia/Shanghai">Asia/Shanghai</option><option value="Asia/Tokyo">Asia/Tokyo</option><option value="Europe/London">Europe/London</option><option value="America/New_York">America/New_York</option></Select></div><div><Label>主题</Label><Select name="theme" defaultValue={settings.theme}><option value="dark">暗色 · 灰雾与黄铜</option><option value="light">明亮 · 旧纸档案</option></Select></div></div><div><Label>每章篇幅</Label><Select name="chapterLength" defaultValue={settings.chapterLength??"long"}><option value="long">长篇 · 1500–2500 字</option><option value="standard">标准 · 1200–1800 字</option><option value="brief">简洁 · 800–1200 字</option></Select></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="allowNonCanonGeo" defaultChecked={settings.allowNonCanonGeo !== false}/>允许非原作补写地名</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="animations" defaultChecked={settings.animations}/>允许克制动画</label><Button type="submit"><Save className="size-4"/>保存设置</Button></form></CardContent></Card></div>
<Card><CardHeader><div><h2 className="serif text-xl">生活画像与 AI 叙事</h2><p className="mt-1 text-xs text-muted">敏感资料按“仅本机、摘要、完整”逐类控制；API Key 只保存在服务端本地文件，不会写入浏览器或备份。</p></div></CardHeader><CardContent className="grid gap-4 md:grid-cols-[1fr_auto] md:items-center"><div className="grid gap-2 text-xs sm:grid-cols-3"><span className="flex items-center gap-2 text-muted"><ShieldCheck className="size-4 text-moss"/>画像授权版本 {personalProfile.consentVersion}</span><span className="text-muted">文本：{adventureStatus?.textConfigured?"已配置":"本地回退"}</span><span className="text-muted">图像：{adventureStatus?.imageConfigured?"已配置":"程序化回退"}</span><span className="text-muted">协议：{adventureStatus?.protocol??"本地"}</span><span className="text-muted">叙事模型：{adventureStatus?.narrativeModel??"local-narrative"}</span><span className="text-muted">裁定模型：{adventureStatus?.adjudicatorModel??"local-adjudicator"}</span><span className="text-muted">图像模型：{adventureStatus?.imageModel||"未配置"}</span></div><Button onClick={()=>setProfileOpen(true)}><BrainCircuit className="size-4"/>编辑生活画像</Button><div className="md:col-span-2"><p className="mb-2 text-xs font-medium text-muted-strong">最近 AI 请求审计</p><div className="space-y-2">{aiLogs.map((log)=><details key={log.id} className="rounded-md border border-border bg-panel-soft p-3 text-xs"><summary className="cursor-pointer flex items-center justify-between gap-3"><span>{log.provider||"local"} · {log.model}</span><span className={log.status==="success"?"text-moss":log.status==="error"?"text-danger":"text-warning"}>{log.status}</span></summary><p className="mt-2 text-muted">上下文指纹：{log.contextHash.slice(0,16)||"无"} · {new Date(log.createdAt).toLocaleString("zh-CN")}</p><pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap break-all text-[10px] leading-5 text-muted">{log.contextPreview||"未发送云端上下文"}</pre></details>)}{!aiLogs.length&&<p className="text-xs text-muted">尚无 AI 请求记录。</p>}</div></div></CardContent></Card><PersonalProfileDialog open={profileOpen} onClose={()=>setProfileOpen(false)}/><AISettingsPanel/><AIUsagePanel/><ContentAuditPanel/><div className="grid gap-5 lg:grid-cols-3"><Card><CardHeader><div><h2 className="serif text-xl">完整 JSON</h2><p className="mt-1 text-xs text-muted">角色、序列、任务、账本、习惯与设置。</p></div></CardHeader><CardContent className="space-y-3"><Button className="w-full" onClick={doExport}><Download className="size-4"/>导出 JSON 备份</Button><Button variant="secondary" className="w-full" onClick={()=>jsonInput.current?.click()}><Upload className="size-4"/>导入并替换</Button><input ref={jsonInput} hidden type="file" accept="application/json" onChange={e=>e.target.files?.[0]&&doImport(e.target.files[0])}/></CardContent></Card>
<Card><CardHeader><div><h2 className="serif text-xl">任务 CSV</h2><p className="mt-1 text-xs text-muted">适合在表格中查看或批量补充任务。</p></div></CardHeader><CardContent className="space-y-3"><Button className="w-full" onClick={doCsvExport}><HardDriveDownload className="size-4"/>导出任务 CSV</Button><Button variant="secondary" className="w-full" onClick={()=>csvInput.current?.click()}><Upload className="size-4"/>导入任务 CSV</Button><input ref={csvInput} hidden type="file" accept=".csv,text/csv" onChange={e=>e.target.files?.[0]&&doCsvImport(e.target.files[0])}/></CardContent></Card>
<Card><CardHeader><div><h2 className="serif text-xl">存储状态</h2><p className="mt-1 text-xs text-muted">浏览器数据可能在清理站点数据时消失。</p></div></CardHeader><CardContent className="space-y-3"><div className="flex justify-between"><span className="text-sm text-muted">任务</span><Badge>{quests}</Badge></div><div className="flex justify-between"><span className="text-sm text-muted">结算记录</span><Badge>{completions}</Badge></div><Button variant="danger" className="w-full" onClick={wipe}><Trash2 className="size-4"/>清除全部数据</Button></CardContent></Card></div>
<p className="text-xs leading-5 text-muted">非官方个人同人工具。原作名称与设定版权归原作者及相关权利方所有；本项目不提供商业服务，也不将危险仪式转换为现实指令。</p></div>}









